/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_o19s_es_ltr_ranker_dectree_JniNoBranchTree */

#ifndef _Included_com_o19s_es_ltr_ranker_dectree_JniNoBranchTree
#define _Included_com_o19s_es_ltr_ranker_dectree_JniNoBranchTree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_o19s_es_ltr_ranker_dectree_JniNoBranchTree
 * Method:    createEnsemble
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_o19s_es_ltr_ranker_dectree_JniNoBranchTree_createEnsemble
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_o19s_es_ltr_ranker_dectree_JniNoBranchTree
 * Method:    destroyEnsemble
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_o19s_es_ltr_ranker_dectree_JniNoBranchTree_destroyEnsemble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_o19s_es_ltr_ranker_dectree_JniNoBranchTree
 * Method:    addTree
 * Signature: (JB[I[F)I
 */
JNIEXPORT jint JNICALL Java_com_o19s_es_ltr_ranker_dectree_JniNoBranchTree_addTree
  (JNIEnv *, jclass, jlong, jbyte, jintArray, jfloatArray);

/*
 * Class:     com_o19s_es_ltr_ranker_dectree_JniNoBranchTree
 * Method:    evalMultiple
 * Signature: (J[Lcom/o19s/es/ltr/ranker/DenseFeatureVector;[F)V
 */
JNIEXPORT void JNICALL Java_com_o19s_es_ltr_ranker_dectree_JniNoBranchTree_evalMultiple
  (JNIEnv *, jclass, jlong, jobjectArray, jfloatArray);

/*
 * Class:     com_o19s_es_ltr_ranker_dectree_JniNoBranchTree
 * Method:    eval
 * Signature: (J[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_o19s_es_ltr_ranker_dectree_JniNoBranchTree_eval
  (JNIEnv *, jclass, jlong, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
